hoaproject/W3

Application/View/Shared/Main.xyl
Without:
With (Firefox OS 2.1):
=> Add meta theme-color

Data/Etc/Locale/Fr/Index.po
=> Fix typo in french translation

Application/Resource/Fallback.php, Application/View/Shared/Definition/Comment.xyl, Application/View/Shared/Overlay/Comment.xyl
Normal (without the focus):
Focused:
See the thread. We can answer, upvote, downvote, edit and remove comments.
Thanks @Pierozi the server-part!
=> Set up comments

Application/View/Shared/Main.xyl
=> Add header anchors

Application/View/En/Literature.xyl, Application/View/Fr/Literature.xyl, Application/View/Shared/Welcome.xyl
Related to https://github.com/hoaproject/Ustring/issues/28.
=> Move `Hoa\String` to `Hoa\Ustring`

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
Since https://github.com/hoaproject/Router/pull/33.
=> New contributor

Application/View/Shared/Event.xyl, Application/View/Shared/Event/Hoaapex15.xyl
=> Draft the Hoa Apex 3rd edition page

Application/View/En/Literature.xyl, Application/View/Fr/Literature.xyl, Application/View/Shared/Welcome.xyl
Deploy https://github.com/hoaproject/Test/pull/37.
=> Add documentation links to `Hoa\Test`

Application/View/Shared/Main.xyl
=> Add favicon

Application/View/Shared/Welcome.xyl
=> Add Pickle's logo

Application/View/En/Literature.xyl, Application/View/Fr/Literature.xyl, Application/View/Shared/Welcome.xyl
https://github.com/hoaproject/Filter/issues/3
=> Remove `Hoa\Filter`.

Application/View/En/Source.xyl, Application/View/Fr/Source.xyl
We are removing this sections please see #87.
=> Remove the archives related section, fix #87

Application/View/Shared/Main.xyl
=> Search: Add a close button

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl, Application/View/Shared/Welcome.xyl
It replaces the ML and it is a sponsor.
=> View: Add Discourse

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
See https://github.com/hoaproject/Central/pull/38.
=> New contributor: @zackkatz!

Application/Public/index.php
https on static links for avoid auto redirection.
=> TLS certificate

Application/View/Shared/Main.xyl
Certificate for search.hoa-project.net has been configured.
=> Update Search link to https secure url

Application/View/Shared/Main.xyl
Certificate for piwik.hoa-project.net has been configured.
=> Update Piwik link to https secure url

Application/View/En/Source.xyl, Application/View/Fr/Source.xyl
=> Source: Mention Gitlab

Application/View/Shared/Welcome.xyl
Fix https://github.com/hoaproject/W3/issues/86.
=> View: Add Wallabag to Who Use

Application/View/Shared/Welcome.xyl
Fix https://github.com/hoaproject/W3/issues/114.
=> View: Add PMSIpilot logo

Application/View/Shared/Welcome.xyl
Move the logo in the right section.
=> View: Move Brand Brothers logo in good section

Application/View/Shared/Overlay/Map.xyl
fix https://github.com/hoaproject/W3/issues/127
=> Map: Update OSM link to openstreetmap to fit certificate.

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
=> New contributor: @arnegroskurth!

Application/View/En/Source.xyl, Application/View/Fr/Source.xyl, Application/View/Shared/Welcome.xyl
Change pikacode url
@hywan please check commit message to be sure it's respect hoaproject/Central#61
=> doc(pikacode) Change pikacode url to v2

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
Related to https://github.com/hoaproject/Central/pull/71.
=> New contributor: @samundra!

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
See https://github.com/hoaproject/Central/pull/72.
=> New contributor: @SerafimArts!

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
See https://github.com/hoaproject/Central/pull/73.
Welcome on board!
=> New contributor: @mathroc!

Application/View/En/Literature.xyl, Application/View/Fr/Literature.xyl, Application/View/Shared/Welcome.xyl
See https://github.com/hoaproject/Central/issues/90.
=> feat(view) Remove abandonned library.

Application/View/En/Community.xyl, Application/View/Fr/Community.xyl
Add contributors @rodion-k and @rexfordkelly
=> chore(contributors) add Contributors @rodion-k and @rexfordkelly

Application/View/Fr/Community.xyl
=> chore(contributors) Add @jwage & @SilverFire
